name: Build examples using YoWASP

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  examples:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: install packages
        run: |
          python --version
          pip --version
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ yowasp-yosys yowasp-nextpnr-himbaechel-gowin
      - name: build examples
        run: |
          cd examples
          YOSYS=yowasp-yosys NEXTPNR=yowasp-nextpnr-himbaechel-gowin make all
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
            name: bitstreams
            path: examples/*.fs
